using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SchemaRender.Generator;

/// <summary>
/// Emits C# source code for schema classes.
/// </summary>
internal static class SchemaEmitter
{
    public static string Emit(SchemaModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using SchemaRender;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        var sealedModifier = model.IsSealed ? "sealed " : "";
        sb.AppendLine($"partial class {model.ClassName} : ISchema");
        sb.AppendLine("{");

        // Generate Write method
        EmitWriteMethod(sb, model);

        // Generate helper methods if needed
        var needsDurationHelper = model.Properties.Any(p =>
            p.TypeKind == PropertyTypeKind.TimeSpan && p.TimeFormat == "Iso8601Duration");

        if (needsDurationHelper)
        {
            sb.AppendLine();
            EmitFormatDurationHelper(sb);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitFormatDurationHelper(StringBuilder sb)
    {
        sb.AppendLine("    private static string FormatDuration(global::System.TimeSpan duration)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (duration.TotalHours >= 1)");
        sb.AppendLine("        {");
        sb.AppendLine("            var hours = (int)duration.TotalHours;");
        sb.AppendLine("            var minutes = duration.Minutes;");
        sb.AppendLine("            return minutes > 0 ? $\"PT{hours}H{minutes}M\" : $\"PT{hours}H\";");
        sb.AppendLine("        }");
        sb.AppendLine("        return $\"PT{(int)duration.TotalMinutes}M\";");
        sb.AppendLine("    }");
    }

    private static void EmitWriteMethod(StringBuilder sb, SchemaModel model)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Writes this schema as JSON-LD to the specified writer.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public void Write(Utf8JsonWriter w)");
        sb.AppendLine("    {");
        sb.AppendLine("        w.WriteStartObject();");
        sb.AppendLine("        w.WriteString(\"@context\", \"https://schema.org\");");
        sb.AppendLine($"        w.WriteString(\"@type\", \"{model.SchemaTypeName}\");");

        foreach (var prop in model.Properties)
        {
            EmitPropertyWrite(sb, prop);
        }

        sb.AppendLine("        w.WriteEndObject();");
        sb.AppendLine("    }");
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;

        if (char.IsLower(name[0]))
            return name;

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static void EmitPropertyWrite(StringBuilder sb, SchemaPropertyModel prop)
    {
        sb.AppendLine();

        if (prop.IsNullable || !prop.IsRequired)
        {
            // Wrap in null check
            var nullCheck = prop.TypeKind == PropertyTypeKind.Array
                ? $"this.{prop.PropertyName} is {{ Count: > 0 }}"
                : $"this.{prop.PropertyName} is not null";

            sb.AppendLine($"        if ({nullCheck})");
            sb.AppendLine("        {");
            EmitPropertyWriteCore(sb, prop, "            ");
            sb.AppendLine("        }");
        }
        else
        {
            EmitPropertyWriteCore(sb, prop, "        ");
        }
    }

    private static void EmitPropertyWriteCore(StringBuilder sb, SchemaPropertyModel prop, string indent)
    {
        var propAccess = $"this.{prop.PropertyName}";

        // Handle nullable value type access
        if (prop.IsNullable && IsValueType(prop.TypeKind))
        {
            propAccess = $"this.{prop.PropertyName}.Value";
        }

        switch (prop.TypeKind)
        {
            case PropertyTypeKind.String:
                sb.AppendLine($"{indent}w.WriteString(\"{prop.JsonName}\", {propAccess});");
                break;

            case PropertyTypeKind.Boolean:
                sb.AppendLine($"{indent}w.WriteBoolean(\"{prop.JsonName}\", {propAccess});");
                break;

            case PropertyTypeKind.Integer:
                sb.AppendLine($"{indent}w.WriteNumber(\"{prop.JsonName}\", {propAccess});");
                break;

            case PropertyTypeKind.Number:
                sb.AppendLine($"{indent}w.WriteNumber(\"{prop.JsonName}\", {propAccess});");
                break;

            case PropertyTypeKind.TimeSpan:
                EmitTimeSpanWrite(sb, prop, propAccess, indent);
                break;

            case PropertyTypeKind.DateTime:
                EmitDateTimeWrite(sb, prop, propAccess, indent);
                break;

            case PropertyTypeKind.DateOnly:
                sb.AppendLine($"{indent}w.WriteString(\"{prop.JsonName}\", {propAccess}.ToString(\"yyyy-MM-dd\"));");
                break;

            case PropertyTypeKind.Uri:
                sb.AppendLine($"{indent}w.WriteString(\"{prop.JsonName}\", {propAccess}.ToString());");
                break;

            case PropertyTypeKind.Array:
                EmitArrayWrite(sb, prop, indent);
                break;

            case PropertyTypeKind.NestedSchema:
                sb.AppendLine($"{indent}w.WritePropertyName(\"{prop.JsonName}\");");
                sb.AppendLine($"{indent}{propAccess}.Write(w);");
                break;
        }
    }

    private static void EmitTimeSpanWrite(StringBuilder sb, SchemaPropertyModel prop, string propAccess, string indent)
    {
        switch (prop.TimeFormat)
        {
            case "TotalMinutes":
                sb.AppendLine($"{indent}w.WriteNumber(\"{prop.JsonName}\", (int){propAccess}.TotalMinutes);");
                break;

            case "TotalSeconds":
                sb.AppendLine($"{indent}w.WriteNumber(\"{prop.JsonName}\", (int){propAccess}.TotalSeconds);");
                break;

            default: // Iso8601Duration
                sb.AppendLine($"{indent}w.WriteString(\"{prop.JsonName}\", FormatDuration({propAccess}));");
                break;
        }
    }

    private static void EmitDateTimeWrite(StringBuilder sb, SchemaPropertyModel prop, string propAccess, string indent)
    {
        switch (prop.DateFormat)
        {
            case "DateOnly":
                sb.AppendLine($"{indent}w.WriteString(\"{prop.JsonName}\", {propAccess}.ToString(\"yyyy-MM-dd\"));");
                break;

            default: // Iso8601
                sb.AppendLine($"{indent}w.WriteString(\"{prop.JsonName}\", {propAccess}.ToString(\"O\"));");
                break;
        }
    }

    private static void EmitArrayWrite(StringBuilder sb, SchemaPropertyModel prop, string indent)
    {
        sb.AppendLine($"{indent}w.WritePropertyName(\"{prop.JsonName}\");");
        sb.AppendLine($"{indent}w.WriteStartArray();");
        sb.AppendLine($"{indent}foreach (var item in this.{prop.PropertyName})");
        sb.AppendLine($"{indent}{{");

        var elementType = prop.ElementType ?? "string";

        // Determine how to write the element
        if (elementType == "string" || elementType == "System.String")
        {
            sb.AppendLine($"{indent}    w.WriteStringValue(item);");
        }
        else if (elementType == "int" || elementType == "System.Int32" ||
                 elementType == "long" || elementType == "System.Int64")
        {
            sb.AppendLine($"{indent}    w.WriteNumberValue(item);");
        }
        else if (elementType == "double" || elementType == "System.Double" ||
                 elementType == "decimal" || elementType == "System.Decimal")
        {
            sb.AppendLine($"{indent}    w.WriteNumberValue(item);");
        }
        else if (elementType == "bool" || elementType == "System.Boolean")
        {
            sb.AppendLine($"{indent}    w.WriteBooleanValue(item);");
        }
        else
        {
            // Assume it's an ISchema
            sb.AppendLine($"{indent}    item.Write(w);");
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine($"{indent}w.WriteEndArray();");
    }

    private static bool IsValueType(PropertyTypeKind kind)
    {
        return kind switch
        {
            PropertyTypeKind.Boolean => true,
            PropertyTypeKind.Integer => true,
            PropertyTypeKind.Number => true,
            PropertyTypeKind.TimeSpan => true,
            PropertyTypeKind.DateTime => true,
            PropertyTypeKind.DateOnly => true,
            _ => false
        };
    }
}
